#!/bin/bash

echoUsage() {
  echo ""
  echo "Invalid command"
  echo "Usage:"
  echo "  rclone-backup-tool [INPUT_FOLDER] [OUTPUT_FOLDER]"
  echo ""
  echo "Transfer all files of input folder to output remote in a folder
  with data timestamp at name in a model 'backup_%d-%m-%y'. This is script 
  is not recursive, don't backup folders and folders content."
}

if [ -z "$1" ]
then
  echoUsage
  exit 1
fi

if [ -z "$2" ]
then
  echoUsage
  exit 1
fi

FOLDER_NAME=$(date +'backup_%d-%m-%y')
rclone mkdir $2:/$FOLDER_NAME
echo "" > $FOLDER_NAME.log

archives=$(find $1 -maxdepth 1 -not -type d)
for archive in $archives; do
  md5sum $1/$archive > $archive.md5
  rclone sync -v $1/$archive.md5 $2:/$FOLDER_NAME/ &>> $FOLDER_NAME.log
  if [ $? -ne 0 ]
  then
    echo "!!! Error in backup file $archive.md5 !!!" >> $FOLDER_NAME.log
  fi

  rclone sync -v $1/$archive $2:/$FOLDER_NAME/ &>> $FOLDER_NAME.log
  if [ $? -ne 0 ]
  then
    echo "!!! Error in backup file $archive !!!" >> $FOLDER_NAME.log
  fi
done
